<#
.SYNOPSIS
    Sends scale test reports via email.

.PARAMETER ReportPaths
    Array of HTML report file paths to attach.

.PARAMETER ResourceGroupName
    Name of the resource group (used in subject line).

.PARAMETER To
    Email recipients. Default: nilay.shah@microsoft.com

.PARAMETER SmtpServer
    SMTP server. Default: smtp.office365.com

.PARAMETER From
    Sender email address.

.EXAMPLE
    .\Send-ScaleTestReport.ps1 -ReportPaths @("report1.html","report2.html") -ResourceGroupName "TDPR-RG-abc"
#>

[CmdletBinding()]
param(
    [string[]]$ReportPaths,
    [string]$ResourceGroupName = "",
    [string]$To = "nilay.shah@microsoft.com",
    [string]$SmtpServer = "smtp.office365.com",
    [int]$SmtpPort = 587,
    [string]$From = "",
    [PSCredential]$Credential
)

$date = Get-Date -Format "yyyy-MM-dd"
$subject = "[TDPR Scale Test] Daily Report — $date"
if ($ResourceGroupName) { $subject += " — $ResourceGroupName" }

# Build HTML body with executive summary
$body = @"
<html>
<head><style>
body { font-family: 'Segoe UI', Arial, sans-serif; color: #333; }
h2 { color: #0078d4; }
.summary { background: #f0f6ff; border-left: 4px solid #0078d4; padding: 12px 16px; margin: 16px 0; }
</style></head>
<body>
<h2>TDPR Scale Test — Daily Report</h2>
<div class="summary">
<p><strong>Date:</strong> $date</p>
<p><strong>Resource Group:</strong> $ResourceGroupName</p>
<p><strong>Reports attached:</strong> $($ReportPaths.Count) HTML report(s)</p>
</div>
<p>Please open the attached HTML reports in a browser for full interactive charts and analysis.</p>
<ul>
$(foreach ($rp in $ReportPaths) { "<li>$(Split-Path $rp -Leaf)</li>" })
</ul>
<p style="color:#888; font-size:12px;">Auto-generated by TDPR Scale Test Pipeline</p>
</body>
</html>
"@

# Validate report files exist
$attachments = @()
foreach ($rp in $ReportPaths) {
    if (Test-Path $rp) {
        $attachments += $rp
        Write-Host "  Attaching: $(Split-Path $rp -Leaf)" -ForegroundColor Green
    } else {
        Write-Warning "Report not found: $rp"
    }
}

if ($attachments.Count -eq 0) {
    Write-Warning "No valid report files to send."
    return
}

# Send email
$mailParams = @{
    To         = $To
    Subject    = $subject
    Body       = $body
    BodyAsHtml = $true
    Attachments = $attachments
}

if ($From) { $mailParams.From = $From }
if ($SmtpServer -and $From) {
    $mailParams.SmtpServer = $SmtpServer
    $mailParams.Port = $SmtpPort
    $mailParams.UseSsl = $true
    if ($Credential) { $mailParams.Credential = $Credential }

    try {
        Send-MailMessage @mailParams
        Write-Host "✅ Email sent to $To" -ForegroundColor Green
    } catch {
        Write-Warning "Failed to send email via SMTP: $_"
        Write-Host "Reports saved locally. You can share them manually:" -ForegroundColor Yellow
        $attachments | ForEach-Object { Write-Host "  $_" }
    }
} else {
    Write-Host "SMTP not configured. Reports available locally:" -ForegroundColor Yellow
    $attachments | ForEach-Object { Write-Host "  $_" }
    Write-Host "`nTo enable email, provide -From and -SmtpServer parameters." -ForegroundColor Yellow
    Write-Host "For ADO pipeline, use the built-in SendEmail task instead." -ForegroundColor Yellow
}
